#!/usr/bin/env sh

# command arguments/user input
search="$*"
search="$(printf "$search" | tr ' ' '+')"

# get the first url from steam search
url="$(curl -s "https://store.steampowered.com/search/?term=$search" | grep -v "excluded" | grep -m 1 -Eo "https://store.steampowered.com/app/[^ >]+/")"

# get title from url
title="$(printf %s "$url" | cut -d '/' -f 6 | tr '_' ' ')"
title="$(command -v figlet > /dev/null && figlet -f slant -t "$title" || printf %s "$title")" # use figlet if installed

# request game page based on url and filter until requirements section
reqs="$(curl -s "$url" --cookie "birthtime=0" | awk '/game_area_sys_req sysreq_content/,0')"

# formatting the text
list="awk '/clear: both;/{exit}1' | grep -o '<[^>]*>.*</[^>]*>' | sed 's/<strong>/    /g;s/<li>/\n    /g;s/<[^>]*>//g'"
case "$reqs" in
	*linux*) # if there is native/linux version
	reqsLinux="$(printf %s "$reqs" | awk '/data-os="linux"/,0' | eval "$list")"
		;;
esac
reqs="$(printf %s "$reqs" | eval "$list")" # proton/windows version

# printing the results
printf '%s\n' "$url"
printf '\033[1m%s\033[0m\n' "$title"
[ -n "$reqsLinux" ] && printf 'NATIVE/LINUX REQUIREMENTS:\n%s\n' "$reqsLinux"
printf 'PROTON/WINDOWS REQUIREMENTS:\n%s\n' "$reqs"
